service: memeMaker

frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221s
  
  iamRoleStatements:
    - Effect: Allow
      Action: "sqs:*"
      Resource: "*"
    - Effect: Allow
      Action: "sns:*"
      Resource: "*"
    - Effect: Allow
      Action: "dynamodb:*"
      Resource: "*"
    - Effect: Allow
      Action: "s3:*"
      Resource: "*"

custom:
  stage: "${opt:stage, self:provider.stage}"
  functionsDir: src/4-framework/functions
  webpack:
    webpackConfig: 'webpack.config.js'
    excludeFiles: tests/**
    includeModules: true
  
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

resources:
  # users module resources
  - ${file(${self:custom.functionsDir}/aws/resources/users/dynamodb/users-dynamodb.yml)}

  # memes module resources
  - ${file(${self:custom.functionsDir}/aws/resources/meme/dynamodb/meme-dynamodb.yml)}
  - ${file(${self:custom.functionsDir}/aws/resources/meme/sqs/meme-sqs.yml)}
  - ${file(${self:custom.functionsDir}/aws/resources/meme/s3/meme-s3.yml)}
functions:
  - ${file(${self:custom.functionsDir}/aws/functions/users/functions.yml)}
  - ${file(${self:custom.functionsDir}/aws/functions/auth/functions.yml)}
  - ${file(${self:custom.functionsDir}/aws/functions/meme/functions.yml)}
