Resources:
  MemesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: memes
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: user_id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      BillingMode: PROVISIONED
      StreamSpecification:
        StreamViewType: NEW_IMAGE